// This file is auto-generated by Blog Agent.
// Do not edit manually.

export const generatedPosts = [
  {
    "id": "1",
    "title": "MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE 분석과 실무 시사점",
    "excerpt": "'MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE'가 왜 중요한지 설명하고, 원문에서 확인되는 기술적 함의를 실무 관점에서 정리한다.",
    "category": "Security",
    "date": "2026-04-14",
    "readTime": "2 min",
    "slug": "ms-agent-does-not-properly-sanitize-commands-sent-to-its-shell-tool-allowing-for-rce",
    "tags": [
      "analysis",
      "blog-agent",
      "rce"
    ],
    "content": "# MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE 분석과 실무 시사점\n\n'MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE'가 왜 중요한지 설명하고, 원문에서 확인되는 기술적 함의를 실무 관점에서 정리한다.\n\n## 들어가며\n\nMS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE는 단순한 뉴스 한 줄로 흘려보낼 주제가 아니라, 실제 운영과 방어 판단에 영향을 줄 수 있는 기술적 신호를 담고 있다. 이 글은 원문을 그대로 옮기기보다 실무자가 무엇을 확인해야 하는지에 초점을 맞춘 초안이다.\n\n## 왜 지금 중요한가\n\nMS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 이 이슈를 지금 봐야 하는 이유는, 단순한 사건 소개가 아니라 실제 의사결정에 바로 연결될 수 있는 변화 신호를 담고 있기 때문이다.\n\n실무적으로 보면 MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE와 관련된 팀은 무엇이 발생했는지뿐 아니라, 그 변화가 운영 절차와 방어 우선순위를 어떻게 바꾸는지까지 함께 이해해야 한다.\n## 기술적으로 무엇이 핵심인가\n\n원문에 드러난 핵심 기술 신호를 정리한다: MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 여기서는 이 사안을 기술적으로 의미 있게 만드는 취약점, 메커니즘, 시스템 동작 변화를 분해해서 볼 필요가 있다.\n\n취약점, 메커니즘, 운영 변화 중 무엇이 핵심인지 분명하게 짚는다. 확인된 사실과 해석을 분리한다. 핵심은 원문이 확인해 주는 사실을 먼저 세우고 그 위에 해석을 얹는 순서를 지키는 것이다.\n## 공격과 방어 관점에서의 함의\n\n악용 가능 경로, 실패 시나리오, 운영 리스크를 설명한다. 만약 이 사안이 취약점이나 노출된 워크플로를 다룬다면 공격자는 이를 더 큰 침해 경로의 한 고리로 연결하려 할 가능성이 높다.\n\n실제로 적용 가능한 방어 조치와 검토 포인트를 정리한다. 좋은 초안이라면 여기서 끝나지 않고 검토해야 할 통제 항목과 아키텍처 수준의 대응 포인트까지 내려와야 한다.\n## 개인 학습 메모\n\n이 주제가 작성자의 학습 흐름과 어떻게 연결되는지 정리한다. 이 대목에서 글은 단순 요약을 벗어나 작성자 관점이 들어간 기술 메모로 바뀐다.\n\n최종 게시 전에 추가 검증이 필요한 부분을 적는다.\n\n## 마무리\n\nMS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE에서 중요한 것은 제목 자체보다 그 아래 숨어 있는 운영상의 교훈이다. MS-Agent does not properly sanitize commands sent to its shell tool, allowing for RCE 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 최종 게시본에서는 이 교훈을 유지하되 근거가 약한 해석은 줄이고, 독자가 바로 적용할 수 있는 다음 행동까지 남겨야 한다.\n\n## 참고 자료\n\n- https://kb.cert.org/vuls/id/431821\n"
  },
  {
    "id": "2",
    "title": "CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read 분석과 실무 시사점",
    "excerpt": "'CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read'가 왜 중요한지 설명하고, 원문에서 확인되는 기술적 함의를 실무 관점에서 정리한다.",
    "category": "AI",
    "date": "2026-04-14",
    "readTime": "2 min",
    "slug": "crewai-contains-multiple-vulnerabilities-including-ssrf-rce-and-local-file-read",
    "tags": [
      "ai",
      "analysis",
      "blog-agent",
      "rce",
      "ssrf"
    ],
    "content": "# CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read 분석과 실무 시사점\n\n'CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read'가 왜 중요한지 설명하고, 원문에서 확인되는 기술적 함의를 실무 관점에서 정리한다.\n\n## 들어가며\n\nCrewAI contains multiple vulnerabilities including SSRF, RCE and local file read는 단순한 뉴스 한 줄로 흘려보낼 주제가 아니라, 실제 운영과 방어 판단에 영향을 줄 수 있는 기술적 신호를 담고 있다. 이 글은 원문을 그대로 옮기기보다 실무자가 무엇을 확인해야 하는지에 초점을 맞춘 초안이다.\n\n## 왜 지금 중요한가\n\nCrewAI contains multiple vulnerabilities including SSRF, RCE and local file read 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 이 이슈를 지금 봐야 하는 이유는, 단순한 사건 소개가 아니라 실제 의사결정에 바로 연결될 수 있는 변화 신호를 담고 있기 때문이다.\n\n실무적으로 보면 CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read와 관련된 팀은 무엇이 발생했는지뿐 아니라, 그 변화가 운영 절차와 방어 우선순위를 어떻게 바꾸는지까지 함께 이해해야 한다.\n## 기술적으로 무엇이 핵심인가\n\n원문에 드러난 핵심 기술 신호를 정리한다: CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 여기서는 이 사안을 기술적으로 의미 있게 만드는 취약점, 메커니즘, 시스템 동작 변화를 분해해서 볼 필요가 있다.\n\n취약점, 메커니즘, 운영 변화 중 무엇이 핵심인지 분명하게 짚는다. 확인된 사실과 해석을 분리한다. 핵심은 원문이 확인해 주는 사실을 먼저 세우고 그 위에 해석을 얹는 순서를 지키는 것이다.\n## 공격과 방어 관점에서의 함의\n\n악용 가능 경로, 실패 시나리오, 운영 리스크를 설명한다. 만약 이 사안이 취약점이나 노출된 워크플로를 다룬다면 공격자는 이를 더 큰 침해 경로의 한 고리로 연결하려 할 가능성이 높다.\n\n실제로 적용 가능한 방어 조치와 검토 포인트를 정리한다. 좋은 초안이라면 여기서 끝나지 않고 검토해야 할 통제 항목과 아키텍처 수준의 대응 포인트까지 내려와야 한다.\n## 개인 학습 메모\n\n이 주제가 작성자의 학습 흐름과 어떻게 연결되는지 정리한다. 이 대목에서 글은 단순 요약을 벗어나 작성자 관점이 들어간 기술 메모로 바뀐다.\n\n최종 게시 전에 추가 검증이 필요한 부분을 적는다.\n\n## 마무리\n\nCrewAI contains multiple vulnerabilities including SSRF, RCE and local file read에서 중요한 것은 제목 자체보다 그 아래 숨어 있는 운영상의 교훈이다. CrewAI contains multiple vulnerabilities including SSRF, RCE and local file read 관련 공지는 실제 공격으로 이어질 수 있는 취약점과 악용 경로를 구체적으로 보여 준다. 최종 게시본에서는 이 교훈을 유지하되 근거가 약한 해석은 줄이고, 독자가 바로 적용할 수 있는 다음 행동까지 남겨야 한다.\n\n## 참고 자료\n\n- https://kb.cert.org/vuls/id/221883\n"
  }
] as const;
